name: Build and Test

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.8
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge -c bioconda python=3.8 bioconductor-deseq2 bioconductor-apeglm rpy2 -y
        pip install git+https://github.com/LouisFaure/deseq2py.git coverage pytest
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        coverage run -m pytest deseq2py/tests/test.py
        coverage report -i -m
        coverage xml -i
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
